## 각 model별 pairwise similarity, confusion matrix 시각화

### 1. OmniVec (ViT)': 'vit_b_16'
<div style="display: flex; ">
  <img src="./result/Final/ViT_.png" alt="./result/Final/ViT_.png" width="450"/>
  <img src="./result/Final/ViT.png" alt="./result/Final/ViT.png" width="450"/>
</div>


### 2. CoCa': 'coca_ViT-B-32'
<div style="display: flex; ">
  <img src="./result/Final/CoCa_.png" alt="./result/Final/CoCa_.png" width="450"/>
  <img src="./result/Final/CoCa.png" alt="./result/Final/CoCa.png" width="450"/>
</div>

### 3. Swin Transformer V2': 'swin_v2_b'
<div style="display: flex; ">
  <img src="./result/Final/SwinTransV2_.png" alt="./result/Final/SwinTransV2_.png" width="450"/>
  <img src="./result/Final/SwinTransV2.png" alt="./result/Final/SwinTransV2.png" width="450"/>
</div>

### 4. ConvNeXt': 'convnext_base'
<div style="display: flex; ">
  <img src="./result/Final/ConvNeXt_.png" alt="./result/Final/ConvNeXt_.png" width="450"/>
  <img src="./result/Final/ConvNeXt.png" alt="./result/Final/ConvNeXt.png" width="450"/>
</div>


### 5. EfficientNetV2': 'efficientnet_v2_s'
<div style="display: flex; ">
  <img src="./result/Final/EfficientNetV2_.png" alt="./result/Final/EfficientNetV2_.png" width="450"/>
  <img src="./result/Final/EfficientNetV2.png" alt="./result/Final/EfficientNetV2.png" width="450"/>
</div>

### 6. RegNet': 'regnet_y_16gf'
<div style="display: flex; ">
  <img src="./result/Final/RegNet_.png" alt="./result/Final/RegNet_.png" width="450"/>
  <img src="./result/Final/RegNet.png" alt="./result/Final/RegNet.png" width="450"/>
</div>

### 7. DeiT': 'deit_base_patch16_224'
<div style="display: flex; ">
  <img src="./result/Final/DeiT_.png" alt="./result/Final/DeiT_.png" width="450"/>
  <img src="./result/Final/DeiT.png" alt="./result/Final/DeiT.png" width="450"/>
</div>

### 8. NFNet': 'nfnet_f0'
<div style="display: flex; ">
  <img src="./result/Final/NFNet_.png" alt="./result/Final/NFNet_.png" width="450"/>
  <img src="./result/Final/NFNet.png" alt="./result/Final/NFNet.png" width="450"/>
</div>

### 9. ResNet18': 'resnet18'
<div style="display: flex; ">
  <img src="./result/Final/ResNet18_.png" alt="./result/Final/ResNet18_.png" width="450"/>
  <img src="./result/Final/ResNet18.png" alt="./result/Final/ResNet18.png" width="450"/>
</div>

### 10. ResNet50': 'resnet50'
<div style="display: flex; ">
  <img src="./result/Final/ResNet50_.png" alt="./result/Final/ResNet50_.png" width="450"/>
  <img src="./result/Final/ResNet50.png" alt="./result/Final/ResNet50.png" width="450"/>
</div>

### 11. EfficientNet B0': 'efficientnet_b0'
<div style="display: flex; ">
  <img src="./result/Final/EfficientNetB0_.png" alt="./result/Final/EfficientNetB0_.png" width="450"/>
  <img src="./result/Final/EfficientNetB0.png" alt="./result/Final/EfficientNetB0.png" width="450"/>
</div>

### 12. EfficientNet B7': 'efficientnet_b7'
<div style="display: flex; ">
  <img src="./result/Final/EfficientNetB7_.png" alt="./result/Final/EfficientNetB7_.png" width="450"/>
  <img src="./result/Final/EfficientNetB7.png" alt="./result/Final/EfficientNetB7.png" width="450"/>
</div>


## 각 model별 embedding 시간 & vector dimension
### **Model: OmniVec (ViT)**   
Processing Time per Image: 0.2601138248548403 seconds   
Vector Dimension: 1000   

### **Model: CoCa**   
Processing Time per Image: 0.0944857086454119 seconds   
Vector Dimension: 512   

### **Model: Swin Transformer V2**   
Processing Time per Image: 0.3420440272970514 seconds   
Vector Dimension: 1000   

### **Model: ConvNeXt**   
Processing Time per Image: 0.2438856703894479 seconds   
Vector Dimension: 1000   

### **Model: EfficientNetV2**   
Processing Time per Image: 0.11241603290641701 seconds   
Vector Dimension: 1000   

### **Model: RegNet**   
Processing Time per Image: 0.3447438950067038 seconds   
Vector Dimension: 1000   

### **Model: DeiT**   
Processing Time per Image: 0.20535810439141242 seconds   
Vector Dimension: 1000   

### **Model: NFNet**   
Processing Time per Image: 0.30200216010376646 seconds   
Vector Dimension: 1000   

### **Model: ResNet18**   
Processing Time per Image: 0.04968958896595043 seconds   
Vector Dimension: 1000   

### **Model: ResNet50**   
Processing Time per Image: 0.10675284626719715 seconds   
Vector Dimension: 1000   

### **Model: EfficientNet B0**   
Processing Time per Image: 0.05325166471711882 seconds   
Vector Dimension: 1000   

### **Model: EfficientNet B7**   
Processing Time per Image: 0.2764782918678535 seconds   
Vector Dimension: 1000   

## 모델별 분석

### **OmniVec (ViT)**
- 유사도 분포: 동일 클래스와 다른 클래스 간 유사도가 분리됨.
- 혼동 행렬: 'BOLD', 'BURR', 'LINE' 클래스에서 좋은 성능.
- 주요 성능 지표: 평균 정확도(57.99%), 주요 클래스 혼동(Tip, Fold).

### **CoCa**
- 유사도 분포: 동일 클래스와 다른 클래스 간 유사도 분포가 많이 겹치는 편.
- 혼동 행렬: 여러 클래스 간 혼동이 발생하며, 전반적으로 중간 정도의 정확도.
- 주요 성능 지표: 평균 정확도(54.34%), 주요 클래스 혼동(Damage, Fold).

### **Swin Transformer V2**
- 유사도 분포: 동일 클래스와 다른 클래스 간 유사도가 분리됨.
- 혼동 행렬: 'BOLD', 'BURR', 'LINE' 클래스에서 좋은 성능.
- 주요 성능 지표: 평균 정확도(59.55%), 주요 클래스 혼동(Tip, Dot).

### **ConvNeXt**
- 유사도 분포: 동일 클래스와 다른 클래스 간 유사도가 분리됨.
- 혼동 행렬: 대부분의 클래스에서 높은 정확도, 'BOLD', 'BURR', 'LINE' 클래스에서 특히 우수.
- 주요 성능 지표: 평균 정확도(62.67%), 주요 클래스 혼동(Tip, Scratch).

### **EfficientNet V2**
- 유사도 분포: 동일 클래스와 다른 클래스 간 유사도가 겹침.
- 혼동 행렬: 다양한 클래스 간 혼동이 발생.
- 주요 성능 지표: 평균 정확도(62.15%), 주요 클래스 혼동(Damage, Line).

### **RegNet**
- 유사도 분포: 동일 클래스와 다른 클래스 간 유사도가 겹침.
- 혼동 행렬: 다양한 클래스 간 혼동이 발생.
- 주요 성능 지표: 평균 정확도(61.63%), 주요 클래스 혼동(Dot, Ring).

### **DeiT**
- 유사도 분포: 동일 클래스와 다른 클래스 간 유사도가 겹치는 부분 존재.
- 혼동 행렬: 'BURR', 'DOT', 'SCRATCH' 클래스에서 혼동이 많음.
- 주요 성능 지표: 평균 정확도(54.86%), 주요 클래스 혼동(Damage, Tip).

### **NFNet**
- 유사도 분포: 동일 클래스와 다른 클래스 간 유사도가 분리됨.
- 혼동 행렬: 'BURR', 'TIP' 클래스에서 혼동이 많음.
- 주요 성능 지표: 평균 정확도(50.17%), 주요 클래스 혼동(Fold, Scratch).

### **ResNet18**
- 유사도 분포: 동일 클래스와 다른 클래스 간 유사도가 분리됨.
- 혼동 행렬: 'BURR', 'DOT' 클래스에서 혼동이 많음.
- 주요 성능 지표: 평균 정확도(61.11%), 주요 클래스 혼동(Line, React).

### **ResNet50**
- 유사도 분포: 동일 클래스와 다른 클래스 간 유사도가 분리됨.
- 혼동 행렬: 'BOLD', 'BURR' 클래스에서 좋은 성능.
- 주요 성능 지표: 평균 정확도(61.63%), 주요 클래스 혼동(Fold, Scratch).

### **EfficientNet B0**
- 유사도 분포: 동일 클래스와 다른 클래스 간 유사도가 많이 겹침.
- 혼동 행렬: 여러 클래스 간 혼동이 발생하며, 전반적으로 중간 이하의 정확도.
- 주요 성능 지표: 평균 정확도(57.99%), 주요 클래스 혼동(Dot, Fold).

### **EfficientNet B7**
- 유사도 분포: 동일 클래스와 다른 클래스 간 유사도가 분리됨.
- 혼동 행렬: 'BOLD', 'BURR' 클래스에서 특히 우수한 성능.
- 주요 성능 지표: 평균 정확도(54.86%), 주요 클래스 혼동(Line, Scratch).


OmniVec (ViT): 57.99%   
CoCa: 54.34%   
Swin Transformer V2: 59.55%   
ConvNeXt: 62.67%   
EfficientNetV2: 62.15%   
RegNet: 61.63%   
DeiT: 54.86%   
NFNet: 50.17%   
ResNet18: 61.11%   
ResNet50: 61.63%   
EfficientNet B0: 57.99%   
EfficientNet B7: 54.86%   

최고의 모델: ConvNeXt
평균 정확도: 62.67%


## 최종 선택 모델 : **ConvNeXt**

### 선택 이유 : 
### 1. 높은 평균 정확도 : ConvNeXt 모델의 평균 정확도 -> 62.67% (평가한 모델들 중 가장 높은 정확도)
### 2. 유사도 분포 : 동일 클래스(평균 0.85) & 다른 클래스(평균 0.65) 간 유사도 분포 명확히 분리 -> 구분 용이
### 3. 혼동 행렬 : 클래스간 혼동이 적음 -> 전반적인 분류 성능이 뛰어남 


In [ ]:
### 2024 Jun 12
### 각 model별 pairwise similarity 시각화

import torch
import torchvision.transforms as transforms
from PIL import Image
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
import time
import os
import ssl
import matplotlib.pyplot as plt
import seaborn as sns
from open_clip import create_model_and_transforms
import timm  # Import timm for additional models
import torchvision.models as models

# SSL 인증서 설정
import certifi
os.environ['SSL_CERT_FILE'] = certifi.where()
ssl._create_default_https_context = ssl._create_unverified_context

class CoCaImg2Vec():
    def __init__(self, model_name, pretrained, cuda=False):
        self.model, _, self.transform = create_model_and_transforms(model_name, pretrained=pretrained)
        self.device = torch.device("cuda" if cuda else "cpu")
        self.model = self.model.to(self.device)
        self.model.eval()

    def get_vec(self, img):
        image = self.transform(img).unsqueeze(0).to(self.device)
        with torch.no_grad():
            embedding = self.model.encode_image(image).cpu().numpy().flatten()
        return embedding

class Img2Vec():
    def __init__(self, model_name, cuda=False):
        self.device = torch.device("cuda" if cuda else "cpu")
        self.transform = transforms.Compose([
            transforms.Resize((224, 224)),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
        ])
        try:
            if model_name.startswith("coca_"):
                self.model, _, self.transform = create_model_and_transforms(model_name, pretrained='mscoco_finetuned_laion2b_s13b_b90k')
            elif hasattr(models, model_name):
                self.model = getattr(models, model_name)(pretrained=True).to(self.device)
            else:
                self.model = timm.create_model(model_name, pretrained=True).to(self.device)
        except AttributeError:
            raise ValueError(f"Model {model_name} not available in torchvision.models or timm")
        except RuntimeError as e:
            if "No pretrained weights exist" in str(e):
                self.model = timm.create_model(model_name, pretrained=False).to(self.device)
            else:
                raise e
        self.model.eval()

    def get_vec(self, img):
        if self.model is None:
            return None
        image = self.transform(img).unsqueeze(0).to(self.device)
        with torch.no_grad():
            embedding = self.model(image)
        embedding_np = embedding.cpu().numpy().flatten()
        return embedding_np

def load_images_from_folder(folder):
    images = []
    labels = []
    valid_image_extensions = ['.jpg', '.jpeg', '.png', '.bmp', '.tiff']
    for class_folder_name in os.listdir(folder):
        class_folder_path = os.path.join(folder, class_folder_name)
        if not os.path.isdir(class_folder_path):
            continue
        for filename in os.listdir(class_folder_path):
            img_path = os.path.join(class_folder_path, filename)
            if os.path.splitext(filename)[1].lower() in valid_image_extensions:
                img = Image.open(img_path).convert('RGB')
                images.append(img)
                labels.append(class_folder_name)
    return images, labels

def pairwise_similarity_distribution(embeddings, labels):
    same_class_sims = []
    diff_class_sims = []

    num_embeddings = len(embeddings)
    for i in range(num_embeddings):
        for j in range(i + 1, num_embeddings):
            sim = cosine_similarity([embeddings[i]], [embeddings[j]])[0][0]
            if labels[i] == labels[j]:
                same_class_sims.append(sim)
            else:
                diff_class_sims.append(sim)
    
    return same_class_sims, diff_class_sims

def normalize_similarity_scores(scores):
    min_score = min(scores)
    max_score = max(scores)
    normalized_scores = [(score - min_score) / (max_score - min_score) for score in scores]
    return normalized_scores

def plot_similarity_distribution(same_class_sims, diff_class_sims, model_name, x_range):
    plt.hist(same_class_sims, bins=50, alpha=0.5, label='Same Class', density=True, range=x_range)
    plt.hist(diff_class_sims, bins=50, alpha=0.5, label='Different Class', density=True, range=x_range)
    plt.xlabel('Cosine Similarity')
    plt.ylabel('Density')
    plt.title(f'Similarity Distribution for {model_name}')
    plt.legend()
    plt.show()

def classify_images(model_dict, folder_path, cuda=False):
    images, labels = load_images_from_folder(folder_path)
    results = {}

    for model_display_name, model_name in model_dict.items():
        print(f"Evaluating model {model_name}")
        if model_name.startswith("coca_"):
            img2vec = CoCaImg2Vec(model_name, pretrained='mscoco_finetuned_laion2b_s13b_b90k', cuda=cuda)
        else:
            img2vec = Img2Vec(model_name, cuda=cuda)
        if img2vec.model is None:
            continue

        start_time = time.time()
        embeddings = [img2vec.get_vec(img) for img in images]
        embeddings = [e for e in embeddings if e is not None]
        embeddings = np.array(embeddings)
        processing_time = (time.time() - start_time) / len(images)

        same_class_sims, diff_class_sims = pairwise_similarity_distribution(embeddings, labels)
        same_class_sims = normalize_similarity_scores(same_class_sims)
        diff_class_sims = normalize_similarity_scores(diff_class_sims)

        results[model_display_name] = {
            'same_class_sims': same_class_sims,
            'diff_class_sims': diff_class_sims,
            'processing_time': processing_time
        }

    global_xlim = (0, 1)
    for model_name, result in results.items():
        plot_similarity_distribution(result['same_class_sims'], result['diff_class_sims'], model_name, global_xlim)

    return results

if __name__ == "__main__":
    folder_path = './data-gatter/train_L'

    model_dict = {
        'OmniVec (ViT)': 'vit_b_16',
        'CoCa': 'coca_ViT-B-32',
        'Swin Transformer V2': 'swin_v2_b',
        'ConvNeXt': 'convnext_base',
        'EfficientNetV2': 'efficientnet_v2_s',
        'RegNet': 'regnet_y_16gf',
        'DeiT': 'deit_base_patch16_224',
        'NFNet': 'nfnet_f0',
        'ResNet18': 'resnet18',
        'ResNet50': 'resnet50',
        'EfficientNet B0': 'efficientnet_b0',
        'EfficientNet B7': 'efficientnet_b7'
    }

    cuda = torch.cuda.is_available()

    results = classify_images(model_dict, folder_path, cuda)
    for model_name, result in results.items():
        print(f"\nModel: {model_name}")
        print(f"Processing Time per Image: {result['processing_time']}")


In [ ]:
### 2024 Jun 12
### 각 model별 confusion matrix 시각화

import os
import ssl
import time
import numpy as np
import torch
from PIL import Image
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics.pairwise import cosine_similarity
import matplotlib.pyplot as plt
import seaborn as sns
from pinecone import Pinecone, ServerlessSpec
from open_clip import create_model_and_transforms
from torchvision import transforms, models
import timm

# SSL 인증서 설정
import certifi
os.environ['SSL_CERT_FILE'] = certifi.where()
ssl._create_default_https_context = ssl._create_unverified_context

class CoCaImg2Vec():
    def __init__(self, model_name, pretrained, cuda=False):
        self.model, _, self.transform = create_model_and_transforms(model_name, pretrained=pretrained)
        self.device = torch.device("cuda" if cuda else "cpu")
        self.model = self.model.to(self.device)
        self.model.eval()

    def get_vec(self, img):
        image = self.transform(img).unsqueeze(0).to(self.device)
        with torch.no_grad():
            embedding = self.model.encode_image(image).cpu().numpy().flatten()
        return embedding

class Img2Vec():
    def __init__(self, model_name, cuda=False):
        self.device = torch.device("cuda" if cuda else "cpu")
        if model_name.startswith("coca_"):
            self.model, _, self.transform = create_model_and_transforms(model_name, pretrained='mscoco_finetuned_laion2b_s13b_b90k')
        else:
            try:
                self.model = getattr(models, model_name)(pretrained=True).to(self.device)
            except AttributeError:
                try:
                    self.model = timm.create_model(model_name, pretrained=True).to(self.device)
                except RuntimeError as e:
                    if "No pretrained weights exist" in str(e):
                        self.model = timm.create_model(model_name, pretrained=False).to(self.device)
                    else:
                        raise e
            self.transform = transforms.Compose([
                transforms.Resize((224, 224)),
                transforms.ToTensor(),
                transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
            ])
        self.model.eval()

    def get_vec(self, img):
        image = self.transform(img).unsqueeze(0).to(self.device)
        with torch.no_grad():
            embedding = self.model(image)
        embedding_np = embedding.cpu().numpy().flatten()
        return embedding_np

def load_images_from_folder(folder):
    images = []
    labels = []
    valid_image_extensions = ['.jpg', '.jpeg', '.png', '.bmp', '.tiff']
    for class_folder_name in os.listdir(folder):
        class_folder_path = os.path.join(folder, class_folder_name)
        if not os.path.isdir(class_folder_path):
            continue
        for filename in os.listdir(class_folder_path):
            img_path = os.path.join(class_folder_path, filename)
            if os.path.splitext(filename)[1].lower() in valid_image_extensions:
                img = Image.open(img_path).convert('RGB')
                images.append(img)
                labels.append(class_folder_name)
    return images, labels

def create_pinecone_index(api_key, index_name, dimension):
    pc = Pinecone(api_key=api_key)
    if index_name not in pc.list_indexes().names():
        pc.create_index(
            name=index_name,
            dimension=dimension,
            metric='cosine',
            spec=ServerlessSpec(
                cloud='aws',
                region='us-east-1'
            )
        )
    return pc.Index(index_name)

def save_embeddings_to_pinecone(index, embeddings, labels, namespace):
    vectors = []
    for i, emb in enumerate(embeddings):
        vectors.append({
            "id": f"vec{i+1}",
            "values": emb.tolist(),
            "metadata": {"label": labels[i]}
        })

    index.upsert(
        vectors=vectors,
        namespace=namespace
    )
    
    return vectors

def classify_images(model_dict, folder_path, cuda=False):
    images, labels = load_images_from_folder(folder_path)
    label_set = sorted(set(labels))
    label_to_index = {label: idx for idx, label in enumerate(label_set)}

    results = {}
    for model_display_name, model_name in model_dict.items():
        print(f"Evaluating model {model_name}")
        if model_name.startswith("coca_"):
            img2vec = CoCaImg2Vec(model_name, pretrained='mscoco_finetuned_laion2b_s13b_b90k', cuda=cuda)
        else:
            img2vec = Img2Vec(model_name, cuda=cuda)
 
        start_time = time.time()
        embeddings = [img2vec.get_vec(img) for img in images]
        embeddings = np.array(embeddings)
        processing_time = (time.time() - start_time) / len(images)

        predicted_labels = []
        for i, embedding in enumerate(embeddings):
            similarities = []
            for j in range(len(images)):
                if i != j:
                    sim = cosine_similarity([embedding], [embeddings[j]])[0][0]
                    similarities.append((sim, labels[j]))

            similarities.sort(reverse=True, key=lambda x: x[0])
            most_similar_label = similarities[0][1]
            predicted_labels.append(most_similar_label)

        true_indices = [label_to_index[label] for label in labels]
        predicted_indices = [label_to_index[label] for label in predicted_labels]

        cm = confusion_matrix(true_indices, predicted_indices)
        report = classification_report(true_indices, predicted_indices, target_names=label_set)

        results[model_display_name] = {
            'confusion_matrix': cm,
            'classification_report': report,
            'processing_time': processing_time
        }

    return results

def visualize_confusion_matrix(cm, model_name, class_names):
    plt.figure(figsize=(10, 8))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=class_names, yticklabels=class_names)
    plt.xlabel('Predicted')
    plt.ylabel('True')
    plt.title(f'Confusion Matrix for {model_name}')
    plt.show()

if __name__ == "__main__":
    folder_path = './data-gatter/train_L'
    model_dict = {
        'OmniVec (ViT)': 'vit_b_16',
        'CoCa': 'coca_ViT-B-32',
        'Swin Transformer V2': 'swin_v2_b',
        'ConvNeXt': 'convnext_base',
        'EfficientNetV2': 'efficientnet_v2_s',
        'RegNet': 'regnet_y_16gf',
        'DeiT': 'deit_base_patch16_224',
        'NFNet': 'nfnet_f0',
        'ResNet18': 'resnet18',
        'ResNet50': 'resnet50',
        'EfficientNet B0': 'efficientnet_b0',
        'EfficientNet B7': 'efficientnet_b7'
    }

    cuda = torch.cuda.is_available()

    results = classify_images(model_dict, folder_path, cuda)
    for model_name, result in results.items():
        print(f"\nModel: {model_name}")
        print(f"Confusion Matrix:\n{result['confusion_matrix']}")  
        print(f"Classification Report:\n{result['classification_report']}")
        print(f"Processing Time per Image: {result['processing_time']}")
        visualize_confusion_matrix(result['confusion_matrix'], model_name, sorted(set(load_images_from_folder(folder_path)[1])))


### Model: OmniVec (ViT)   
Confusion Matrix:   
[[ 9  0  1  0  1  0  3  0  0  0  2  0]   
 [ 0 14  2  0  0  0  0  0  0  0  0  0]   
 [ 1  1  8  0  1  0  0  2  0  0  1  2]   
 [ 1  2  0  8  1  1  1  0  0  0  2  0]   
 [ 1  0  0  0 11  4  0  0  0  0  0  0]   
 [ 0  0  0  0  5  9  0  0  0  0  0  2]   
 [ 2  0  0  1  1  0  9  0  0  0  3  0]   
 [ 1  0  2  0  1  1  0  8  0  0  1  2]   
 [ 0  0  1  0  1  0  1  0 11  0  1  1]   
 [ 0  0  0  0  0  0  0  0  0  5  0  1]   
 [ 1  0  2  2  0  1  3  1  0  0  5  1]   
 [ 1  0  4  0  1  1  2  0  0  0  1  6]]   

Classification Report:   
              precision    recall  f1-score   support

        BOLD       0.53      0.56      0.55        16
      BUBBLE       0.82      0.88      0.85        16
        BURR       0.40      0.50      0.44        16
      DAMAGE       0.73      0.50      0.59        16
         DOT       0.48      0.69      0.56        16
        DUST       0.53      0.56      0.55        16
        FOLD       0.47      0.56      0.51        16
        LINE       0.73      0.50      0.59        16
       REACT       1.00      0.69      0.81        16
        RING       1.00      0.83      0.91         6
     SCRATCH       0.31      0.31      0.31        16
         TIP       0.40      0.38      0.39        16

    accuracy                           0.57       182
    macro avg      0.62      0.58      0.59       182
    weighted avg   0.60      0.57      0.57       182

Processing Time per Image: 0.2244774823660379   

### Model: CoCa   
Confusion Matrix:   
[[ 8  0  1  0  0  1  2  0  0  0  3  1]   
 [ 0 14  1  0  0  0  0  0  0  0  1  0]   
 [ 3  1  5  0  0  1  0  2  0  0  0  4]   
 [ 0  2  1  9  1  1  1  0  1  0  0  0]   
 [ 0  0  0  0 11  4  0  0  0  0  1  0]   
 [ 1  0  1  0  3  8  0  1  0  0  2  0]   
 [ 6  0  0  1  0  0  8  0  0  0  1  0]   
 [ 0  0  3  0  0  2  0 10  0  0  1  0]   
 [ 1  0  2  1  1  1  0  0  8  0  1  1]   
 [ 0  0  0  0  0  0  0  0  0  5  0  1]   
 [ 2  3  0  0  1  3  1  2  0  0  4  0]   
 [ 4  0  3  0  1  0  0  0  0  1  1  6]]   
 
Classification Report:   
              precision    recall  f1-score   support

        BOLD       0.32      0.50      0.39        16
      BUBBLE       0.70      0.88      0.78        16
        BURR       0.29      0.31      0.30        16
      DAMAGE       0.82      0.56      0.67        16
         DOT       0.61      0.69      0.65        16
        DUST       0.38      0.50      0.43        16
        FOLD       0.67      0.50      0.57        16
        LINE       0.67      0.62      0.65        16
       REACT       0.89      0.50      0.64        16
        RING       0.83      0.83      0.83         6
     SCRATCH       0.27      0.25      0.26        16
         TIP       0.46      0.38      0.41        16

    accuracy                           0.53       182
    macro avg      0.58      0.54      0.55       182
    weighted avg   0.56      0.53      0.53       182

Processing Time per Image: 0.09076410859495729   

### Model: Swin Transformer V2
Confusion Matrix:   
[[10  0  1  0  1  0  2  0  0  0  2  0]   
 [ 0 15  1  0  0  0  0  0  0  0  0  0]   
 [ 2  1  6  0  0  1  0  3  0  0  0  3]   
 [ 0  1  0  8  0  1  1  0  1  0  4  0]   
 [ 0  0  0  0  9  7  0  0  0  0  0  0]   
 [ 1  0  1  0  4 10  0  0  0  0  0  0]   
 [ 1  0  0  1  0  3 10  0  0  0  1  0]   
 [ 0  0  2  1  0  0  0 11  0  0  0  2]   
 [ 0  0  0  0  1  0  2  0 11  0  1  1]   
 [ 0  0  0  0  0  0  0  0  0  5  0  1]   
 [ 0  0  0  2  3  1  2  1  1  0  6  0]   
 [ 2  0  5  0  0  0  2  1  1  0  0  5]]   
Classification Report:   
              precision    recall  f1-score   support

        BOLD       0.62      0.62      0.62        16
      BUBBLE       0.88      0.94      0.91        16
        BURR       0.38      0.38      0.38        16
      DAMAGE       0.67      0.50      0.57        16
         DOT       0.50      0.56      0.53        16
        DUST       0.43      0.62      0.51        16
        FOLD       0.53      0.62      0.57        16
        LINE       0.69      0.69      0.69        16
       REACT       0.79      0.69      0.73        16
        RING       1.00      0.83      0.91         6
     SCRATCH       0.43      0.38      0.40        16
         TIP       0.42      0.31      0.36        16

    accuracy                           0.58       182
    macro avg      0.61      0.60      0.60       182
    weighted avg   0.59      0.58      0.58       182

Processing Time per Image: 0.30342312173528985   

### Model: ConvNeXt   
Confusion Matrix:   
[[11  0  0  0  0  2  2  0  0  0  1  0]   
 [ 0 15  0  0  1  0  0  0  0  0  0  0]   
 [ 0  1  7  0  1  0  0  2  0  0  0  5]   
 [ 1  2  0  8  0  1  1  0  1  0  2  0]   
 [ 1  0  1  0 11  3  0  0  0  0  0  0]   
 [ 2  0  1  0  4  9  0  0  0  0  0  0]   
 [ 2  0  0  0  0  1  9  0  0  0  3  1]   
 [ 0  0  3  0  0  0  0 11  0  0  1  1]   
 [ 1  0  0  0  0  1  0  0 12  0  2  0]   
 [ 0  0  0  0  0  0  0  0  0  5  0  1]   
 [ 1  0  0  3  1  2  1  1  1  0  5  1]   
 [ 1  0  3  0  1  0  1  0  0  1  0  9]]   
Classification Report:   
              precision    recall  f1-score   support

        BOLD       0.55      0.69      0.61        16
      BUBBLE       0.83      0.94      0.88        16
        BURR       0.47      0.44      0.45        16
      DAMAGE       0.73      0.50      0.59        16
         DOT       0.58      0.69      0.63        16
        DUST       0.47      0.56      0.51        16
        FOLD       0.64      0.56      0.60        16
        LINE       0.79      0.69      0.73        16
       REACT       0.86      0.75      0.80        16
        RING       0.83      0.83      0.83         6
     SCRATCH       0.36      0.31      0.33        16
         TIP       0.50      0.56      0.53        16

    accuracy                           0.62       182
    macro avg      0.63      0.63      0.63       182
    weighted avg   0.62      0.62      0.61       182

Processing Time per Image: 0.22215243879255359   

### Model: EfficientNetV2   
Confusion Matrix:   
[[ 7  0  1  0  0  4  4  0  0  0  0  0]   
 [ 0 14  0  0  1  0  0  0  1  0  0  0]   
 [ 1  1  8  0  1  0  1  2  0  0  0  2]   
 [ 0  1  0 11  0  1  2  0  0  0  0  1]   
 [ 1  0  0  0 13  2  0  0  0  0  0  0]   
 [ 3  0  1  0  1  8  0  0  0  0  3  0]   
 [ 6  1  0  0  0  1  8  0  0  0  0  0]   
 [ 0  0  2  0  0  0  0 11  0  0  1  2]   
 [ 1  0  1  0  0  0  0  0 13  0  0  1]   
 [ 0  0  0  0  1  0  0  0  0  5  0  0]   
 [ 1  0  0  3  1  2  2  1  0  0  5  1]   
 [ 2  0  3  0  1  0  1  1  0  0  0  8]]   
Classification Report:   
              precision    recall  f1-score   support

        BOLD       0.32      0.44      0.37        16
      BUBBLE       0.82      0.88      0.85        16
        BURR       0.50      0.50      0.50        16
      DAMAGE       0.79      0.69      0.73        16
         DOT       0.68      0.81      0.74        16
        DUST       0.44      0.50      0.47        16
        FOLD       0.44      0.50      0.47        16
        LINE       0.73      0.69      0.71        16
       REACT       0.93      0.81      0.87        16
        RING       1.00      0.83      0.91         6
     SCRATCH       0.56      0.31      0.40        16
         TIP       0.53      0.50      0.52        16

    accuracy                           0.61       182
    macro avg      0.65      0.62      0.63       182
    weighted avg   0.63      0.61      0.61       182

Processing Time per Image: 0.08062792872334575   

### Model: RegNet   
Confusion Matrix:   
[[ 9  0  0  0  0  2  3  0  0  0  0  2]   
 [ 0 14  1  0  1  0  0  0  0  0  0  0]   
 [ 2  1  7  0  1  0  0  0  0  0  0  5]   
 [ 1  1  1  7  1  1  1  0  0  0  3  0]   
 [ 0  0  0  0 11  4  1  0  0  0  0  0]   
 [ 2  0  1  0  4  8  0  0  0  0  1  0]   
 [ 2  0  0  0  0  0 12  0  0  0  2  0]   
 [ 0  0  4  0  0  0  0 10  0  0  0  2]   
 [ 1  0  0  0  0  0  2  0 12  0  1  0]   
 [ 0  0  0  0  0  1  0  0  0  5  0  0]   
 [ 0  0  1  2  2  2  3  0  0  0  6  0]   
 [ 1  0  4  0  1  0  1  0  0  0  0  9]]   
Classification Report:
              precision    recall  f1-score   support

        BOLD       0.50      0.56      0.53        16
      BUBBLE       0.88      0.88      0.88        16
        BURR       0.37      0.44      0.40        16
      DAMAGE       0.78      0.44      0.56        16
         DOT       0.52      0.69      0.59        16
        DUST       0.44      0.50      0.47        16
        FOLD       0.52      0.75      0.62        16
        LINE       1.00      0.62      0.77        16
       REACT       1.00      0.75      0.86        16
        RING       1.00      0.83      0.91         6
     SCRATCH       0.46      0.38      0.41        16
         TIP       0.50      0.56      0.53        16

    accuracy                           0.60       182
    macro avg      0.66      0.62      0.63       182
    weighted avg   0.65      0.60      0.61       182

Processing Time per Image: 0.3328970369401869   

### Model: DeiT   
Confusion Matrix:   
[[ 9  0  0  0  0  2  4  0  0  0  0  1]   
 [ 0 14  0  0  2  0  0  0  0  0  0  0]   
 [ 3  1  6  0  0  1  0  4  0  0  0  1]   
 [ 0  1  0  8  4  0  1  0  0  0  2  0]   
 [ 1  0  0  0  8  6  0  0  0  0  1  0]   
 [ 1  0  0  0  5 10  0  0  0  0  0  0]   
 [ 5  0  0  0  0  0  8  0  0  0  3  0]   
 [ 0  0  3  0  0  0  0 10  0  0  1  2]   
 [ 1  0  0  1  2  1  0  0 11  0  0  0]   
 [ 0  0  0  0  0  0  0  0  0  5  1  0]   
 [ 1  0  0  0  4  1  3  1  0  0  6  0]   
 [ 2  0  7  0  1  0  2  1  1  0  0  2]]   
Classification Report:
              precision    recall  f1-score   support

        BOLD       0.39      0.56      0.46        16
      BUBBLE       0.88      0.88      0.88        16
        BURR       0.38      0.38      0.38        16
      DAMAGE       0.89      0.50      0.64        16
         DOT       0.31      0.50      0.38        16
        DUST       0.48      0.62      0.54        16
        FOLD       0.44      0.50      0.47        16
        LINE       0.62      0.62      0.62        16
       REACT       0.92      0.69      0.79        16
        RING       1.00      0.83      0.91         6
     SCRATCH       0.43      0.38      0.40        16
         TIP       0.33      0.12      0.18        16

    accuracy                           0.53       182
    macro avg      0.59      0.55      0.55       182
    weighted avg   0.57      0.53      0.53       182

Processing Time per Image: 0.18692302048861326   

### Model: NFNet   
Confusion Matrix:   
[[ 6  0  1  0  0  1  6  0  0  0  1  1]   
 [ 0 13  2  1  0  0  0  0  0  0  0  0]   
 [ 1  2  8  0  0  0  0  1  0  0  1  3]   
 [ 0  3  0  7  3  0  0  0  1  0  2  0]   
 [ 0  0  0  2  9  5  0  0  0  0  0  0]   
 [ 1  0  1  0  4  8  0  1  0  0  1  0]   
 [ 4  0  0  1  0  0  7  1  0  0  3  0]   
 [ 0  0  1  0  0  2  2  9  0  0  0  2]   
 [ 1  0  0  3  2  0  0  0  8  0  2  0]   
 [ 0  0  0  0  0  0  0  0  1  5  0  0]   
 [ 2  0  1  3  2  2  0  0  1  0  5  0]   
 [ 1  0  7  0  0  2  1  2  0  0  0  3]]   
Classification Report:
              precision    recall  f1-score   support

        BOLD       0.38      0.38      0.38        16
      BUBBLE       0.72      0.81      0.76        16
        BURR       0.38      0.50      0.43        16
      DAMAGE       0.41      0.44      0.42        16
         DOT       0.45      0.56      0.50        16
        DUST       0.40      0.50      0.44        16
        FOLD       0.44      0.44      0.44        16
        LINE       0.64      0.56      0.60        16
       REACT       0.73      0.50      0.59        16
        RING       1.00      0.83      0.91         6
     SCRATCH       0.33      0.31      0.32        16
         TIP       0.33      0.19      0.24        16

    accuracy                           0.48       182
    macro avg      0.52      0.50      0.50       182
    weighted avg   0.49      0.48      0.48       182

Processing Time per Image: 0.2516383613858904   

### Model: ResNet18   
Confusion Matrix:   
[[11  0  0  0  0  1  2  0  0  0  2  0]   
 [ 0 14  0  1  0  0  0  0  0  0  1  0]   
 [ 0  1 10  0  1  0  0  0  0  0  1  3]   
 [ 0  3  0  6  1  0  1  0  1  0  4  0]   
 [ 1  0  0  0 11  3  0  0  0  0  1  0]   
 [ 3  0  2  0  2  7  0  0  1  0  1  0]   
 [ 1  0  0  1  0  0  9  0  0  1  3  1]   
 [ 1  0  2  0  2  0  0  9  0  0  1  1]   
 [ 0  0  1  0  0  1  0  0 11  0  2  1]   
 [ 0  0  0  0  0  0  1  0  0  5  0  0]   
 [ 1  0  1  2  1  3  1  0  1  0  6  0]   
 [ 1  0  2  0  1  0  1  0  0  1  0 10]]   
Classification Report:
              precision    recall  f1-score   support

        BOLD       0.58      0.69      0.63        16
      BUBBLE       0.78      0.88      0.82        16
        BURR       0.56      0.62      0.59        16
      DAMAGE       0.60      0.38      0.46        16
         DOT       0.58      0.69      0.63        16
        DUST       0.47      0.44      0.45        16
        FOLD       0.60      0.56      0.58        16
        LINE       1.00      0.56      0.72        16
       REACT       0.79      0.69      0.73        16
        RING       0.71      0.83      0.77         6
     SCRATCH       0.27      0.38      0.32        16
         TIP       0.62      0.62      0.62        16

    accuracy                           0.60       182
    macro avg      0.63      0.61      0.61       182
    weighted avg   0.62      0.60      0.60       182

Processing Time per Image: 0.05888586777907152   

### Model: ResNet50   
Confusion Matrix:   
[[ 9  0  0  0  0  0  4  0  0  0  2  1]   
 [ 0 15  0  0  0  0  1  0  0  0  0  0]   
 [ 2  1  5  0  1  0  0  2  0  0  0  5]   
 [ 0  2  0  9  2  0  2  0  1  0  0  0]   
 [ 0  0  1  0 10  3  1  0  0  0  1  0]   
 [ 0  0  1  0  4  9  0  0  0  0  1  1]   
 [ 2  0  0  0  1  0 12  0  0  0  1  0]   
 [ 0  0  3  0  1  0  1  8  0  0  1  2]   
 [ 1  0  0  0  0  1  3  0 11  0  0  0]   
 [ 0  0  0  0  0  0  0  0  1  5  0  0]   
 [ 1  0  0  0  2  1  2  1  0  0  8  1]   
 [ 1  0  2  0  0  1  2  1  0  0  0  9]]   
Classification Report:
              precision    recall  f1-score   support

        BOLD       0.56      0.56      0.56        16
      BUBBLE       0.83      0.94      0.88        16
        BURR       0.42      0.31      0.36        16
      DAMAGE       1.00      0.56      0.72        16
         DOT       0.48      0.62      0.54        16
        DUST       0.60      0.56      0.58        16
        FOLD       0.43      0.75      0.55        16
        LINE       0.67      0.50      0.57        16
       REACT       0.85      0.69      0.76        16
        RING       1.00      0.83      0.91         6
     SCRATCH       0.57      0.50      0.53        16
         TIP       0.47      0.56      0.51        16

    accuracy                           0.60       182
    macro avg      0.66      0.62      0.62       182
    weighted avg   0.64      0.60      0.61       182

Processing Time per Image: 0.09030402099693215   

### Model: EfficientNet B0   
Confusion Matrix:   
[[ 6  0  1  0  0  1  5  0  0  0  2  1]   
 [ 0 15  1  0  0  0  0  0  0  0  0  0]   
 [ 2  2  4  0  0  1  0  3  0  0  0  4]   
 [ 0  1  0  9  1  1  1  0  1  0  2  0]   
 [ 0  0  0  0 10  3  0  1  0  0  0  2]   
 [ 1  0  1  0  2 10  0  0  0  0  1  1]   
 [ 3  0  0  1  1  0 10  0  0  0  1  0]   
 [ 0  0  5  0  1  0  0  8  0  0  1  1]   
 [ 0  0  1  0  0  1  0  1 12  0  0  1]   
 [ 0  0  0  0  0  1  0  0  0  5  0  0]   
 [ 0  0  0  1  1  3  2  1  0  0  8  0]   
 [ 0  0  5  0  0  2  1  0  2  0  0  6]]   
Classification Report:
              precision    recall  f1-score   support

        BOLD       0.50      0.38      0.43        16
      BUBBLE       0.83      0.94      0.88        16
        BURR       0.22      0.25      0.24        16
      DAMAGE       0.82      0.56      0.67        16
         DOT       0.62      0.62      0.62        16
        DUST       0.43      0.62      0.51        16
        FOLD       0.53      0.62      0.57        16
        LINE       0.57      0.50      0.53        16
       REACT       0.80      0.75      0.77        16
        RING       1.00      0.83      0.91         6
     SCRATCH       0.53      0.50      0.52        16
         TIP       0.38      0.38      0.38        16

    accuracy                           0.57       182
    macro avg      0.60      0.58      0.59       182
    weighted avg   0.58      0.57      0.57       182

Processing Time per Image: 0.04071122342413598   

### Model: EfficientNet B7   
Confusion Matrix:   
[[ 8  0  1  0  0  0  5  0  0  0  1  1]   
 [ 0 15  0  0  1  0  0  0  0  0  0  0]   
 [ 1  0  7  0  0  2  0  3  0  0  0  3]   
 [ 0  0  0 10  1  1  0  0  1  0  3  0]   
 [ 0  1  0  0 10  5  0  0  0  0  0  0]   
 [ 1  0  1  0  4  7  0  0  0  0  2  1]   
 [ 5  0  0  0  0  0  9  0  0  0  2  0]   
 [ 0  0  6  0  0  1  1  6  0  0  0  2]   
 [ 1  0  0  0  1  2  0  0 10  0  1  1]   
 [ 0  0  0  0  1  0  0  0  0  5  0  0]   
 [ 1  0  1  2  2  1  3  0  0  0  6  0]   
 [ 2  0  5  0  0  1  2  0  1  1  0  4]]   
Classification Report:
              precision    recall  f1-score   support

        BOLD       0.42      0.50      0.46        16
      BUBBLE       0.94      0.94      0.94        16
        BURR       0.33      0.44      0.38        16
      DAMAGE       0.83      0.62      0.71        16
         DOT       0.50      0.62      0.56        16
        DUST       0.35      0.44      0.39        16
        FOLD       0.45      0.56      0.50        16
        LINE       0.67      0.38      0.48        16
       REACT       0.83      0.62      0.71        16
        RING       0.83      0.83      0.83         6
     SCRATCH       0.40      0.38      0.39        16
         TIP       0.33      0.25      0.29        16

    accuracy                           0.53       182
   macro avg       0.57      0.55      0.55       182
weighted avg       0.56      0.53      0.54       182

Processing Time per Image: 0.19879127465761626   

In [ ]:
import numpy as np

# 각 모델의 혼동 행렬을 여기에 추가
confusion_matrices = {
    'OmniVec (ViT)': np.array([
        [9, 0, 1, 0, 1, 0, 3, 0, 0, 0, 2, 0],
        [0, 14, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 8, 0, 1, 0, 0, 2, 0, 0, 1, 2],
        [1, 2, 0, 8, 1, 1, 1, 0, 0, 0, 2, 0],
        [1, 0, 0, 0, 11, 4, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 5, 9, 0, 0, 0, 0, 0, 2],
        [2, 0, 0, 1, 1, 0, 9, 0, 0, 0, 3, 0],
        [1, 0, 2, 0, 1, 1, 0, 8, 0, 0, 1, 2],
        [0, 0, 1, 0, 1, 0, 1, 0, 11, 0, 1, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 1],
        [1, 0, 2, 2, 0, 1, 3, 1, 0, 0, 5, 1],
        [1, 0, 4, 0, 1, 1, 2, 0, 0, 0, 1, 6]
    ]),
    'CoCa': np.array([
        [8, 0, 1, 0, 0, 1, 2, 0, 0, 0, 3, 1],
        [0, 14, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [3, 1, 5, 0, 0, 1, 0, 2, 0, 0, 0, 4],
        [0, 2, 1, 9, 1, 1, 1, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 11, 4, 0, 0, 0, 0, 1, 0],
        [1, 0, 1, 0, 3, 8, 0, 1, 0, 0, 2, 0],
        [6, 0, 0, 1, 0, 0, 8, 0, 0, 0, 1, 0],
        [0, 0, 3, 0, 0, 2, 0, 10, 0, 0, 1, 0],
        [1, 0, 2, 1, 1, 1, 0, 0, 8, 0, 1, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 1],
        [2, 3, 0, 0, 1, 3, 1, 2, 0, 0, 4, 0],
        [4, 0, 3, 0, 1, 0, 0, 0, 0, 1, 1, 6]
    ]),
    'Swin Transformer V2': np.array([
        [10, 0, 1, 0, 1, 0, 2, 0, 0, 0, 2, 0],
        [0, 15, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [2, 1, 6, 0, 0, 1, 0, 3, 0, 0, 0, 3],
        [0, 1, 0, 8, 0, 1, 1, 0, 1, 0, 4, 0],
        [0, 0, 0, 0, 9, 7, 0, 0, 0, 0, 0, 0],
        [1, 0, 1, 0, 4, 10, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 1, 0, 3, 10, 0, 0, 0, 1, 0],
        [0, 0, 2, 1, 0, 0, 0, 11, 0, 0, 0, 2],
        [0, 0, 0, 0, 1, 0, 2, 0, 11, 0, 1, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 1],
        [0, 0, 0, 2, 3, 1, 2, 1, 1, 0, 6, 0],
        [2, 0, 5, 0, 0, 0, 2, 1, 1, 0, 0, 5]
    ]),
    'ConvNeXt': np.array([
        [11, 0, 0, 0, 0, 2, 2, 0, 0, 0, 1, 0],
        [0, 15, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 7, 0, 1, 0, 0, 2, 0, 0, 0, 5],
        [1, 2, 0, 8, 0, 1, 1, 0, 1, 0, 2, 0],
        [1, 0, 1, 0, 11, 3, 0, 0, 0, 0, 0, 0],
        [2, 0, 1, 0, 4, 9, 0, 0, 0, 0, 0, 0],
        [2, 0, 0, 0, 0, 1, 9, 0, 0, 0, 3, 1],
        [0, 0, 3, 0, 0, 0, 0, 11, 0, 0, 1, 1],
        [1, 0, 0, 0, 0, 1, 0, 0, 12, 0, 2, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 1],
        [1, 0, 0, 3, 1, 2, 1, 1, 1, 0, 5, 1],
        [1, 0, 3, 0, 1, 0, 1, 0, 0, 1, 0, 9]
    ]),
    'EfficientNetV2': np.array([
        [7, 0, 1, 0, 0, 4, 4, 0, 0, 0, 0, 0],
        [0, 14, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
        [1, 1, 8, 0, 1, 0, 1, 2, 0, 0, 0, 2],
        [0, 1, 0, 11, 0, 1, 2, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 13, 2, 0, 0, 0, 0, 0, 0],
        [3, 0, 1, 0, 1, 8, 0, 0, 0, 0, 3, 0],
        [6, 1, 0, 0, 0, 1, 8, 0, 0, 0, 0, 0],
        [0, 0, 2, 0, 0, 0, 0, 11, 0, 0, 1, 2],
        [1, 0, 1, 0, 0, 0, 0, 0, 13, 0, 0, 1],
        [0, 0, 0, 0, 1, 0, 0, 0, 0, 5, 0, 0],
        [1, 0, 0, 3, 1, 2, 2, 1, 0, 0, 5, 1],
        [2, 0, 3, 0, 1, 0, 1, 1, 0, 0, 0, 8]
    ]),
    'RegNet': np.array([
        [9, 0, 0, 0, 0, 2, 3, 0, 0, 0, 0, 2],
        [0, 14, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
        [2, 1, 7, 0, 1, 0, 0, 0, 0, 0, 0, 5],
        [1, 1, 1, 7, 1, 1, 1, 0, 0, 0, 3, 0],
        [0, 0, 0, 0, 11, 4, 1, 0, 0, 0, 0, 0],
        [2, 0, 1, 0, 4, 8, 0, 0, 0, 0, 1, 0],
        [2, 0, 0, 0, 0, 0, 12, 0, 0, 0, 2, 0],
        [0, 0, 4, 0, 0, 0, 0, 10, 0, 0, 0, 2],
        [1, 0, 0, 0, 0, 0, 2, 0, 12, 0, 1, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 5, 0, 0],
        [0, 0, 1, 2, 2, 2, 3, 0, 0, 0, 6, 0],
        [1, 0, 4, 0, 1, 0, 1, 0, 0, 0, 0, 9]
    ]),
    'DeiT': np.array([
        [9, 0, 0, 0, 0, 2, 4, 0, 0, 0, 0, 1],
        [0, 14, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
        [3, 1, 6, 0, 0, 1, 0, 4, 0, 0, 0, 1],
        [0, 1, 0, 8, 4, 0, 1, 0, 0, 0, 2, 0],
        [1, 0, 0, 0, 8, 6, 0, 0, 0, 0, 1, 0],
        [1, 0, 0, 0, 5, 10, 0, 0, 0, 0, 0, 0],
        [5, 0, 0, 0, 0, 0, 8, 0, 0, 0, 3, 0],
        [0, 0, 3, 0, 0, 0, 0, 10, 0, 0, 1, 2],
        [1, 0, 0, 1, 2, 1, 0, 0, 11, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 1, 0],
        [1, 0, 0, 0, 4, 1, 3, 1, 0, 0, 6, 0],
        [2, 0, 7, 0, 1, 0, 2, 1, 1, 0, 0, 2]
    ]),
    'NFNet': np.array([
        [6, 0, 1, 0, 0, 1, 6, 0, 0, 0, 1, 1],
        [0, 13, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 2, 8, 0, 0, 0, 0, 1, 0, 0, 1, 3],
        [0, 3, 0, 7, 3, 0, 0, 0, 1, 0, 2, 0],
        [0, 0, 0, 2, 9, 5, 0, 0, 0, 0, 0, 0],
        [1, 0, 1, 0, 4, 8, 0, 1, 0, 0, 1, 0],
        [4, 0, 0, 1, 0, 0, 7, 1, 0, 0, 3, 0],
        [0, 0, 1, 0, 0, 2, 2, 9, 0, 0, 0, 2],
        [1, 0, 0, 3, 2, 0, 0, 0, 8, 0, 2, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 5, 0, 0],
        [2, 0, 1, 3, 2, 2, 0, 0, 1, 0, 5, 0],
        [1, 0, 7, 0, 0, 2, 1, 2, 0, 0, 0, 3]
    ]),
    'ResNet18': np.array([
        [11, 0, 0, 0, 0, 1, 2, 0, 0, 0, 2, 0],
        [0, 14, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 1, 10, 0, 1, 0, 0, 0, 0, 0, 1, 3],
        [0, 3, 0, 6, 1, 0, 1, 0, 1, 0, 4, 0],
        [1, 0, 0, 0, 11, 3, 0, 0, 0, 0, 1, 0],
        [3, 0, 2, 0, 2, 7, 0, 0, 1, 0, 1, 0],
        [1, 0, 0, 1, 0, 0, 9, 0, 0, 1, 3, 1],
        [1, 0, 2, 0, 2, 0, 0, 9, 0, 0, 1, 1],
        [0, 0, 1, 0, 0, 1, 0, 0, 11, 0, 2, 1],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 5, 0, 0],
        [1, 0, 1, 2, 1, 3, 1, 0, 1, 0, 6, 0],
        [1, 0, 2, 0, 1, 0, 1, 0, 0, 1, 0, 10]
    ]),
    'ResNet50': np.array([
        [9, 0, 0, 0, 0, 0, 4, 0, 0, 0, 2, 1],
        [0, 15, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
        [2, 1, 5, 0, 1, 0, 0, 2, 0, 0, 0, 5],
        [0, 2, 0, 9, 2, 0, 2, 0, 1, 0, 0, 0],
        [0, 0, 1, 0, 10, 3, 1, 0, 0, 0, 1, 0],
        [0, 0, 1, 0, 4, 9, 0, 0, 0, 0, 1, 1],
        [2, 0, 0, 0, 1, 0, 12, 0, 0, 0, 1, 0],
        [0, 0, 3, 0, 1, 0, 1, 8, 0, 0, 1, 2],
        [1, 0, 0, 0, 0, 1, 3, 0, 11, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 5, 0, 0],
        [1, 0, 0, 0, 2, 1, 2, 1, 0, 0, 8, 1],
        [1, 0, 2, 0, 0, 1, 2, 1, 0, 0, 0, 9]
    ]),
    'EfficientNet B0': np.array([
        [6, 0, 1, 0, 0, 1, 5, 0, 0, 0, 2, 1],
        [0, 15, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [2, 2, 4, 0, 0, 1, 0, 3, 0, 0, 0, 4],
        [0, 1, 0, 9, 1, 1, 1, 0, 1, 0, 2, 0],
        [0, 0, 0, 0, 10, 3, 0, 1, 0, 0, 0, 2],
        [1, 0, 1, 0, 2, 10, 0, 0, 0, 0, 1, 1],
        [3, 0, 0, 1, 1, 0, 10, 0, 0, 0, 1, 0],
        [0, 0, 5, 0, 1, 0, 0, 8, 0, 0, 1, 1],
        [0, 0, 1, 0, 0, 1, 0, 1, 12, 0, 0, 1],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 5, 0, 0],
        [0, 0, 0, 1, 1, 3, 2, 1, 0, 0, 8, 0],
        [0, 0, 5, 0, 0, 2, 1, 0, 2, 0, 0, 6]
    ]),
    'EfficientNet B7': np.array([
        [8, 0, 1, 0, 0, 0, 5, 0, 0, 0, 1, 1],
        [0, 15, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 7, 0, 0, 2, 0, 3, 0, 0, 0, 3],
        [0, 0, 0, 10, 1, 1, 0, 0, 1, 0, 3, 0],
        [0, 1, 0, 0, 10, 5, 0, 0, 0, 0, 0, 0],
        [1, 0, 1, 0, 4, 7, 0, 0, 0, 0, 2, 1],
        [5, 0, 0, 0, 0, 0, 9, 0, 0, 0, 2, 0],
        [0, 0, 6, 0, 0, 1, 1, 6, 0, 0, 0, 2],
        [1, 0, 0, 0, 1, 2, 0, 0, 10, 0, 1, 1],
        [0, 0, 0, 0, 1, 0, 0, 0, 0, 5, 0, 0],
        [1, 0, 1, 2, 2, 1, 3, 0, 0, 0, 6, 0],
        [2, 0, 5, 0, 0, 1, 2, 0, 1, 1, 0, 4]
    ])

}

# 각 모델의 평균 정확도 계산 함수
def calculate_average_accuracy(confusion_matrix):
    accuracy_per_class = []
    for i in range(len(confusion_matrix)):
        true_positives = confusion_matrix[i, i]
        total_samples = np.sum(confusion_matrix[i, :])
        accuracy = true_positives / total_samples if total_samples > 0 else 0
        accuracy_per_class.append(accuracy)
    
    average_accuracy = np.mean(accuracy_per_class)
    return average_accuracy

# 각 모델의 평균 정확도 계산
average_accuracies = {model: calculate_average_accuracy(cm) for model, cm in confusion_matrices.items()}

# 결과 출력
for model, accuracy in average_accuracies.items():
    print(f"{model}: {accuracy:.2%}")

# 가장 높은 평균 정확도를 가진 모델 선택
best_model = max(average_accuracies, key=average_accuracies.get)
best_accuracy = average_accuracies[best_model]

print(f"\n최고의 모델: {best_model}")
print(f"평균 정확도: {best_accuracy:.2%}")
